spring:
  profiles.active: dev
---
spring:
  profiles: dev
server.port: 1100
application:
  decryptionKey: 
mysql:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://sjc-dbdl-mysql4:3306/spelladm
  username: spelladm
  password: VJFR0z8A7wB5ti5s9hRfILhgrb9Vqx6i
---
spring:
  profiles: prod
server.port: 1100
application:
  decryptionKey: prod
mysql:
  driverClassName: com.mysql.jdbc.Driver
  url: DB_PROD_URL
  username: DB_PROD_USERNAME
  password: DB_PROD_PASSWORD